// packages/formspec-studio/src/main.tsx
/** @filedesc Entry point for the Studio app; registers the formspec-render custom element and mounts App. */
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { initFormspecEngine, initFormspecEngineTools } from 'formspec-engine';
import 'formspec-webcomponent/formspec-default.css';
import { FormspecRender } from 'formspec-webcomponent';
import { App } from './App';
import './index.css';

if (!customElements.get('formspec-render')) {
  customElements.define('formspec-render', FormspecRender);
}

async function bootstrap(): Promise<void> {
  await initFormspecEngine();
  await initFormspecEngineTools();

  createRoot(document.getElementById('root')!).render(
    <StrictMode>
      <App />
    </StrictMode>
  );
}

void bootstrap();

// examples/react-demo/src/main.tsx
/** @filedesc Entry point for the formspec-react demo app. */
import React from 'react';
import { createRoot } from 'react-dom/client';
import { initFormspecEngine } from '@formspec/engine';
import { emitThemeTokens } from '@formspec/react';

// 1. Library CSS — standalone form styling with --formspec-* variables
import '../../../packages/formspec-react/src/formspec.css';
// 2. App CSS — shell styling (header, submit panel, etc.)
import './globals.css';

import { App } from './App';
import theme from './theme.json';

async function boot() {
    await initFormspecEngine();
    emitThemeTokens(theme.tokens);
    createRoot(document.getElementById('root')!).render(<App />);
}

boot().catch(console.error);
