// examples/shadcn-demo/src/main.tsx
/** @filedesc Entry point: registers formspec-render custom element with the shadcn adapter. */
import React from 'react';
import { createRoot } from 'react-dom/client';
import { FormspecRender, globalRegistry } from 'formspec-webcomponent';
import { shadcnAdapter } from 'formspec-adapters/shadcn';
import { initFormspecEngine } from 'formspec-engine';
import 'formspec-webcomponent/formspec-layout.css';
import './globals.css';
import { App } from './App';

// Initialize WASM engine, register custom element + shadcn adapter
async function boot() {
    await initFormspecEngine();

    customElements.define('formspec-render', FormspecRender);
    globalRegistry.registerAdapter(shadcnAdapter);
    globalRegistry.setAdapter('shadcn');

    createRoot(document.getElementById('root')!).render(<App />);
}

boot().catch(console.error);

// examples/react-demo/src/main.tsx
/** @filedesc Entry point for the formspec-react demo app. */
import React from 'react';
import { createRoot } from 'react-dom/client';
import { initFormspecEngine } from '@formspec/engine';
import { emitThemeTokens } from '@formspec/react';

// 1. Library CSS — standalone form styling with --formspec-* variables
import '../../../packages/formspec-react/src/formspec.css';
// 2. App CSS — shell styling (header, submit panel, etc.)
import './globals.css';

import { App } from './App';
import theme from './theme.json';

async function boot() {
    await initFormspecEngine();
    emitThemeTokens(theme.tokens);
    createRoot(document.getElementById('root')!).render(<App />);
}

boot().catch(console.error);
